### ISSUE TITLE
Suggestion: Add a warning when using React version < 15.5

### ISSUE THREAD

**Issue by tamoore** [brigand/babel-plugin-flow-react-proptypes#104]
It would be good if the plugin could warn you when using it with a react version that is lower then 15.5.

We recently updated this plugin but did not update React and had written a few components that we thought were correctly validated. We discovered after a few hours of investigation the implication of using 1.0.0+ with React < 15.5. (facepalm)

Understandably this was an error and we should have considered the semver implication of going from 0.21.0 to 1.0.0+ 

But I thought it would help if the plugin could warn about the necessity for `prop-types` when it detects React < 15.5

**Comment by brigand** [comment]
Hmm... I'm not quite sure how this would work. An install time warning, compile time, or runtime? Wouldn't you get a compile time error if prop-types isn't installed?

**Comment by tamoore** [comment]
I didn't get one when compiling with `babel-cli`.

I think probably compile time would be best, the react-app-preset outputs an error because it requires `NODE_ENV` to be set. 

https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js#L50

Works pretty well, be happy to do a pull request for that if you think it's a good idea.

**Comment by brigand** [comment]
@tamoore oh, so for npm packages? In an app, webpack/etc would error if prop-types wasn't installed.

There are edge cases where you won't have it installed at compile time (peer dep), or would have it installed when dev'ing the package but not have it in the app (dev dep). So for those cases, we'd have to add a config option to disable it.

I'm just going to note it in the readme for now.

**Comment by brigand** [comment]
Oh, there's already a note in the readme about this.

**Comment by tamoore** [comment]
I don't believe that's the case:

> In an app, webpack/etc would error if prop-types wasn't installed.

We have a webpack pipeline and we didn't receive any warning/errors. 

Certainly agree that the readme note is probably sufficient, if I can confirm that a webpack pipeline will flag the mismatch then it's probably fine.
