### ISSUE TITLE
Support function components

### ISSUE THREAD

**Issue by brigand** [brigand/babel-plugin-flow-react-proptypes#11]
From https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/3#issuecomment-210542458

The basic approach would be checking for a function that has a type definition in its argument `function foo(props: Something) {` that returns `<something>` or `React.createElement()`. 

```js
type FooProps = {name: string};

function Foo(props: FooProps) { 
  return <div>Hello, {props.name}</div>
}
```

What does a function that destructures its arguments look like with flow? I tried this, but it's a syntax error:

```js
function a({x: 1}: SOmeProps) {
  return <div />
}
```

**Comment by STRML** [comment]
Re: destructuring, the correct syntax would be:

```js
type SomeProps = {x: number, y: string};
function AComponent({x, y}: SomeProps) {
  return <div />
}
```

Or it could even be inline:

```js
function AComponent({x, y}: {x: number, y: string}) {
  return <div />
}
```

**Comment by glortho** [comment]
+1 these seem like readily identifiable signatures 👆

**Comment by skovhus** [comment]
It is supported, but just very opinionated, e.g. you cannot use spread, the type needs to be prefixed `Props` and the export needs to be in a specific format

See https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/__test__/fixtures/stateless.input.js

I might have a look at improving this.

**Comment by brigand** [comment]
Fixed thanks to https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/31
