### ISSUE TITLE
Usage of checkPropTypes

### ISSUE THREAD

**Issue by blackxored** [brigand/babel-plugin-flow-react-proptypes#112]
I'm getting this warning with the latest version from npm:
```
Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead
```

**Comment by brigand** [comment]
Does the warning go away if you disable this plugin? We're not using checkPropTypes or React.PropTypes AFAIK.

**Comment by blackxored** [comment]
It might have been a caching issue, for some reason the stack was pointing out here. Please feel free to close for the time being. I think it might be related to another error with VirtualizedList in React Native, but I had to rollback to 0.44. Will report if I face this again.

**Comment by brigand** [comment]
Sure, I'll reopen if you think this plugin is the issue.
