### ISSUE TITLE
When importing an enum type, prop gets marked as required

### ISSUE THREAD

**Issue by arahansen** [brigand/babel-plugin-flow-react-proptypes#113]
I'm seeing some odd behavior with imported flow types.

For example:
```javascript
// values.js
export type Values = 1 | 2 | 3 | 'string' | void;

// MyComp.js
import React from 'react'
import type { Values } from './values';

class MyComp extends React.Component {
  props: {
    values?: Values
  }
  render() {
    ...
  }
}
```

If I move the Values definition into the same file as MyComp, the prop-types are generated correctly.

Expected Output:
values is an optional prop type

Actual Output:
I see runtime errors that suggest that `value` is a required prop-type:
```
Warning: Failed prop type: The prop `value` is marked as required in `MyComp`, but its value is `undefined`.
```

Seems this issue could be related to this commit? https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/93

**Comment by brigand** [comment]
@arahansen can you share `values.js`?

**Comment by brigand** [comment]
@arahansen I think I fixed it. Please give this a try

```
npm install https://s3.us-east-2.amazonaws.com/brigand-misc/babel-plugin-flow-react-proptypes-3.4.0.tgz
```
If it checks out, I'll publish it.

**Comment by obartra** [comment]
I repro the issue with the `https://s3.us-east-2.amazonaws.com/brigand-misc/babel-plugin-flow-react-proptypes-3.4.0.tgz` one too

**Comment by arahansen** [comment]
Yep, looks like I'm still getting the error @brigand

**Comment by arahansen** [comment]
Let me know if there's any additional debugging details I can provide. I'm not great with AST transformations, so not sure how much help I can be with debugging the plugin directly.

**Comment by darekkay** [comment]
FYI, I came across the same issue today, version 3.3.0.

**Comment by arahansen** [comment]
This seems to have been resolved for me
