### ISSUE TITLE
Exported type includes bloat in transpiled code

### ISSUE THREAD

**Issue by vass-david** [brigand/babel-plugin-flow-react-proptypes#114]
Input
```javascript
// @flow
import React, { Component } from 'react';

export type Props = {
  text: string,
};

const Test = (props: Props) => (
  <div>{props.text}</div>
);

export default Test;
```

Output:
```javascript
import React, { Component } from 'react';

if (typeof exports !== 'undefined') Object.defineProperty(exports, 'babelPluginFlowReactPropTypes_proptype_Props', {
  value: {
    text: require('prop-types').string.isRequired
  }
});


var Test = function Test(props) {
  return React.createElement(
    'div',
    null,
    props.text
  );
};

Test.propTypes = {
  text: require('prop-types').string.isRequired
};
export default Test;
```

My concern is about this part
```javascript
if (typeof exports !== 'undefined') Object.defineProperty(exports, 'babelPluginFlowReactPropTypes_proptype_Props', {
  value: {
    text: require('prop-types').string.isRequired
  }
});
```

It's added when I want to export type. I can see it in README code as well, but without comment so I don't know what is the real meaning of this code. So my two questions are:
* What is the purpose of this code?
* And mainly, how can I turn it off?

It does not do anything bad in my regular builds, but it's failing my tests for some reason, so that's why I'm raising this issue. This is what I see in console:
```javascript
TypeError: Cannot redefine property: babelPluginFlowReactPropTypes_proptype_Props
```
It seems like test are running this code twice for some reason.

**Comment by brigand** [comment]
Hello. That error is quite odd.

> What is the purpose of this code?

It allows you to export types from one file, import it in another, and use that type in another component's propTypes; e.g. `export type Foo = 'a' | 'b'`, `import type {Foo} from '...'`.

> And mainly, how can I turn it off?

You could try removing the `export` in `export type Props`.

---

I pushed a fix as 3.4.1; let me know if that works.

**Comment by vass-david** [comment]
@brigand Thanks for quick response. Really appreciate it, since I really like what this plugin does.

> It allows you to export types from one file, import it in another, and use that type in another component's propTypes; e.g. export type Foo = 'a' | 'b', import type {Foo} from '...'.

In my pipeline I've transpile code to:
* files with stripped flowtypes, so It can be used in non flow code or modules
* files with flowtypes compatible with es5, which are used in other flow modules that use this module
So when I import some exported type, it works perfectly without any special stuff in transpiled code. That's what confused me here. So as I understand, if I import flow types from one file, `babel-plugin-flow-react-proptypes` uses this export for importing proptypes?

> You could try removing the export in export type Props.

In this particular code I need that export because I'm using type in other code, so removing export is not an option.

I will test the fix in afternoon and let you now.

Thanks

**Comment by vass-david** [comment]
It's not published to npm yet and for some reason It does not work when I install it from github :(.
This is in my `package.json`:
```
"babel-plugin-flow-react-proptypes": "git+https://github.com/brigand/babel-plugin-flow-react-proptypes.git",
```

This is build error:
```
ReferenceError: Unknown plugin "flow-react-proptypes" specified in "/Users/davidvass/Work/Test/.babelrc.env.cjs" at 5, attempted to resolve relative to "/Users/davidvass/Work/Test"
```

I've tried to install with yarn and npm 5 as well, same result.

**Comment by vass-david** [comment]
Any update here?

**Comment by brigand** [comment]
You can't install from git because there's a build step.

**Comment by vass-david** [comment]
I see it's in npm now anyway and it works! Thanks a lot!
