### ISSUE TITLE
defaultProps not recognised

### ISSUE THREAD

**Issue by dagda1** [brigand/babel-plugin-flow-react-proptypes#119]
If I have a component like this:
```
export const Button = ({
  onClick = identity,
  className,
  primary,
  inverse,
  disabled,
  children,
  ...rest
}: {
  onClick: identity<*>,
  className: string,
  primary: boolean,
  inverse: boolean,
  disabled: boolean,
  children: Element<*>,
  rest: any
}) =>
  <button
    //etc
```

I am setting onClick to have a defaultProp with `onClick = identity,` but I still get a warning:

>> The prop `onClick` is marked as required in `Button`, but its value is `undefined`

**Comment by brigand** [comment]
Hello,

You should set `Button.defaultProps = { onClick: identity }` or make the prop optional: `onClick?: identity<*>`.

Closing for now, but I can re-open if you have a proposed change.

**Comment by dagda1** [comment]
@brigand I think this is my misunderstanding, I thought if the Prop was required then supplying a defaultProp would fill that requirement.  Is this not the case?

**Comment by brigand** [comment]
@dagda1 not as far as React's concerned. It doesn't know that you're defaulting the prop **inside** the component. You have to use its api (`C.defaultProps`) to define defaults, which is checked before `C.propTypes`.
