### ISSUE TITLE
Support Flow 0.53.0

### ISSUE THREAD

**Issue by echenley** [brigand/babel-plugin-flow-react-proptypes#124]
Flow 0.53.0 removes the `DefaultProps` argument in the `React$Component` generic, and is now simply `React$Component<Props, State>`. https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

I believe this line needs to change to `path.node.superTypeParameters.params[0]`:
https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/index.js#L221

**Comment by brigand** [comment]
Attempted fix: https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/125
