### ISSUE TITLE
[package.json] build is including inline sourcemaps

### ISSUE THREAD

**Issue by rosskevin** [brigand/babel-plugin-flow-react-proptypes#126]
The [build script](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/package.json#L9) needs to start with something like `NODE_ENV=production` to prevent debugging sourcemaps from being included in the package.

Currently stack traces refer to invalid code.

I'll probably fix this as I work on (likely) a PR to help support 0.53.1

**Comment by brigand** [comment]
Fixed in 5.0.1. I look forward to your PR 😄
