### ISSUE TITLE
Not working for Component<Props> with Flow 0.53.0

### ISSUE THREAD

**Issue by k15a** [brigand/babel-plugin-flow-react-proptypes#130]
The second type argument of Component is optional and can be omitted when the component doesn't have state:

> When your component has no state, you only need to pass in a single type argument. The second type argument that represents state will default to undefined. Without state your component definition would look like this:

Working:
```js
class Comp extends React.Component<Props, State> {}
```

Not working:
```js
class Comp extends React.Component<Props> {}
```

**Comment by brigand** [comment]
Thanks! [Silly mistake](https://github.com/brigand/babel-plugin-flow-react-proptypes/commit/0eade4568dc9fa1b748670f66be06ade64d17feb). Released as 5.1.2.
