### ISSUE TITLE
Expected instance of String, received String

### ISSUE THREAD

**Issue by blackxored** [brigand/babel-plugin-flow-react-proptypes#144]
I'm suddenly getting this kind of errors. Was there a breaking change I wasn't aware of?
Using both 9.x.x and 3.4.0. 
Thanks in advance.

**Comment by brigand** [comment]
@blackxored what errors?

**Comment by brigand** [comment]
Oh in the title. Could you give the full error and a code sample that shows the problem?

**Comment by k15a** [comment]
You probably used the uppercase `String` instead of the lowercase `string`. The difference is that the uppercase one is for `new String('hello')` and the lowercase one is for the normal `'string'`.

**Comment by blackxored** [comment]
You're right, that's probably it. I've been working with GraphQL and that seems like someone I'd do 😂

**Comment by brigand** [comment]
Good catch. Closing this for now.
