### ISSUE TITLE
Compatibility with Babel 7?

### ISSUE THREAD

**Issue by rsolomon** [brigand/babel-plugin-flow-react-proptypes#150]
I can't quite get this to work with Babel 7. I know it explicitly lists babel@6 as a dependency, so that may be the root of the issue.

I am able to get it to compile, but it gets hung up on imports that don't seem to exist.

**Comment by brigand** [comment]
@rsolomon hey, thanks for bringing this up.

I'm having trouble finding migration documents for plugin authors. From what I can tell, it's still in beta. Might be best to wait for a stable release.

Could you give the exact errors you're getting, and the related code?

If you want to experiment with it, I'd love any information you can provide. If we can get it reasonably working on both babel majors, that'd be great. I'm guessing we'd move the babel deps to peer deps, and then tweak the plugin code some.

**Comment by rsolomon** [comment]
Yep I'll try to give it a look this week. It is still in Beta, but word on the street is that it'll be heading toward a stable release shortly.

**Comment by marudor** [comment]
7bd55cb6d1c88fa9571c6055f40c9eaafea75004 should've enabled Babel7 support.
Released with 11.2.0

**Comment by rsolomon** [comment]
Hey thanks for the update. I tested this out again, and it looks like I'm having trouble with files with the `'no babel-plugin-flow-react-proptypes';` directive. My guess is that babel is stripping it out, but I'm not sure how to configure it away. Any advice?

**Comment by brigand** [comment]
@rsolomon can you make a reproduction case? If there isn't a clean way to solve it in your environment, I can try adding a comment that does the same thing.

**Comment by haf** [comment]
I've linked this issue from https://github.com/babel/babel/issues/8648#issuecomment-419740411 — from the above comment, I take it you have babel 7 support?

**Comment by brigand** [comment]
@haf I haven't personally tested on 7.x yet. There's the [babel-7 branch](https://github.com/brigand/babel-plugin-flow-react-proptypes/tree/babel-7) from [this PR a year ago](https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/102), but it's likely less work to do it from scratch at this point.

We should change [this][1] to use parametric modules, and the project should be developed against babel 7.

With babel 7 out, a PR would be very welcome. Otherwise, I can likely find time later this week.

[1]: https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/makePropTypesAst.js#L2-L3

**Comment by haf** [comment]
@brigand Thank you for telling me the status. No rush. You have a great project.

**Comment by MaxInMoon** [comment]
@brigand to install the `babel-7` branch, i did `yarn add git://github.com/brigand/babel-plugin-flow-react-proptypes.git#babel-7 -D`, but  this error message `"Cannot find module 'babel-plugin-flow-react-proptypes"` appeared.
What is the process to link the branch-setup with the plugin declaration? Tank you

**Comment by abumalick** [comment]
Don't forget to update that very useful plugin 👍 

I am waiting for support for babel 7 🚀
