### ISSUE TITLE
Type aliases shouldn't be mandatory

### ISSUE THREAD

**Issue by aij** [brigand/babel-plugin-flow-react-proptypes#158]
While trying to get this plugin to work, one of the issues I encountered is that it seems to require superfluous [type aliases](https://flow.org/en/docs/types/aliases/).

If the type is passed directly to `React.Component<>` then no `propTypes` are generated. No error or warning is given either, so it would be very easy for someone to accidentally break runtime prop checking through a perfectly reasonable refactoring.

I created a [minimal reproduction / test case](https://github.com/aij/babel-plugin-flow-react-proptypes/commit/fb961e55d5b58de958ea3a883521906c14c4e081) which hopefully makes the problem clear. Note that the generated snapshot is missing a `Foo.propTypes` assignment.

Any idea why the type alias would matter?

**Comment by brigand** [comment]
Thanks for pointing this out and the test case. Fixed in 13.0.0.
