### ISSUE TITLE
[bug] ExportNamedDeclarations with exportKind: "type" are not transpiled

### ISSUE THREAD

**Issue by Andarist** [brigand/babel-plugin-flow-react-proptypes#167]
This stays untouched by the plugin:
```js
export type {
  NoContentRenderer,
  Alignment,
  CellPosition,
  CellSize,
  OverscanIndicesGetter,
  RenderedSection,
  CellRendererParams,
  Scroll,
} from './types';
```

**Comment by TrySound** [comment]
And this currently breaks react virtualized with a lot of such warnings
![image](https://user-images.githubusercontent.com/5635476/35626221-0e9ddb00-06a6-11e8-864f-3f0b0ebed03d.png)

**Comment by brigand** [comment]
Sorry, somehow missed this issue. 16.0.0.

**Comment by Andarist** [comment]
I confirm that **this** issue is resolved, closing :)
