### ISSUE TITLE
deadCode for esm

### ISSUE THREAD

**Issue by TrySound** [brigand/babel-plugin-flow-react-proptypes#168]
Why `deadCode` can't work with esm? It would be much better to just wrap `propTypes` field with `__DEV__` and treeshake `prop-types` package out. Currently [transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) doesn't affect this plugin output.

**Comment by brigand** [comment]
It could probably be made to work if the bundler is seeing the `import`/`export` statements, but it wouldn't work if babel is compiling ESM to common.js, which is quite common, especially for packages published to npm.

I think ideally we'd have the option for dead code, and an option for common.js or ESM output. I'd want to improve the testing situation before introducing more configuration or features, but I don't have much time to put into it currently.
