### ISSUE TITLE
[bug] ImportDeclarations with importKind: "type" do not account for local specifiers

### ISSUE THREAD

**Issue by Andarist** [brigand/babel-plugin-flow-react-proptypes#176]
**input**

```js
import type { Scroll as GridScroll } from '../Grid';
import type { Scroll } from './types';
```

**output**

```js
import { bpfrpt_proptype_Scroll } from '../Grid';
import { bpfrpt_proptype_Scroll } from './types';
```

Which of course is a clash of identifiers and results in
> [!] (commonjs plugin) SyntaxError: Identifier 'bpfrpt_proptype_Scroll' has already been declared (238:9) in /Users/mateuszburzynski/Desktop/react-virtualized/source/List/List.js

**NOTE**
I'm reporting it but also preparing a fix right now.

**Comment by brigand** [comment]
Cool, thanks for continuing to contribute here 👍

**Comment by TrySound** [comment]
@brigand And I continue to publish broken releases :)

**Comment by Andarist** [comment]
@TrySound I've discovered this quickly because I have a WIP `react-virtualized` branch where I already use rollup for building a flat bundle, which warns me nicely about those broken cases immediately :P One more reason to migrate to rollup there ;)

**Comment by TrySound** [comment]
@Andarist Yeah, you are right.
