### ISSUE TITLE
PropTypes is not defined

### ISSUE THREAD

**Issue by IanVS** [brigand/babel-plugin-flow-react-proptypes#187]
Hi, I recently updated from `2.2.1` up to `17.1.2`, and I've started getting errors like: 

```
Uncaught ReferenceError: PropTypes is not defined
```

It seems that the plugin is not adding the import of `PropTypes` correctly, maybe?  Or is there something else I'm missing?  I'm on react `15.4.2`, in case that matters.

**Comment by brigand** [comment]
@IanVS could you give an example file that causes this issue, and your babel config?

**Comment by TrySound** [comment]
@IanVS Flow changed react interfaces. Not you should specify generics like this
```
import * as React from 'react';

type Props = {

}

type State = {

}

class App1 extends React.Component<Props> {
  render() {}
}

class App2 extends React.Component<Props, State> {
  render() {}
}
```

**Comment by IanVS** [comment]
Right, that's the way with flow 0.53 and above, but I should have mentioned we are still on 0.52.

**Comment by TrySound** [comment]
Perhaps this plugin shouldn't be updated too?

**Comment by IanVS** [comment]
@TrySound are you saying that recent versions of this plugin require flow 0.53 (and/or React 16)?  I can't tell if that's the case from reading the README.  If so, what's the latest version that should be safe for me to use?

**Comment by TrySound** [comment]
It seems like your case should work fine.
https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/__tests__/hoc.js
Did you enable esm support?

**Comment by TrySound** [comment]
Also can you provide transpiled result?

**Comment by brigand** [comment]
It looks like this is the issue:

```js
import React, {PropTypes, Component} from 'react';
```

The `PropTypes` export was removed from React in version 15.0

**Comment by brigand** [comment]
These are the outputs for your files, btw: https://gist.github.com/brigand/3c24152f848fd86521d8c7337d7c56e5

I think if you just delete the 'PropTypes' import in your source code, it'll work.

**Comment by IanVS** [comment]
>The PropTypes export was removed from React in version 15.0

It was removed in react 15.5:

https://reactjs.org/docs/typechecking-with-proptypes.html

We are still on `15.4.2`.

@TrySound, what do you mean by "enable esm support"?  You can see in my `.babelrc` above that I'm using `["es2015", { "modules": false }]`.

Here is what I'm getting, as copied out of the Chrome source tab: https://gist.github.com/IanVS/967e4348f9124d2ed4f4aedf36ba23b2

Removing the import of `PropTypes` from React in the importing file has no effect.

**Comment by IanVS** [comment]
BTW, is there a better way to run a single file through babel and get the output?

**Comment by brigand** [comment]
@IanVS `npx babel file.js`

**Comment by IanVS** [comment]
What adds the `import PropTypes from "prop-types";` at the bottom of your gist?  I can't find that anywhere in my source explorer in chrome (everything there is `require`), but it _is_ there when I run `npx babel` as you said.  

`npx babel ...` even adds the import statement when I set `["flow-react-proptypes", {"useESModules": false}],`, is that correct behavior?

**Comment by brigand** [comment]
That config option should probably be renamed to 'forceESModules' but the behavior is correct. The `'deadCode'` option switches it to use `require`, and `useESModules` overrides that.

> The `useESModules` option forces this plugin to output ES6 module [...]

The import is added by this plugin, but maybe babel is detecting a duplicate import and removing the one we add from the final code? I don't think this plugin is doing that check, but I'm not sure.

**Comment by TrySound** [comment]
It was removed in 16.0. In 15.5 it was just deprecated
