### ISSUE TITLE
Mixed indexers and named properties are not supported

### ISSUE THREAD

**Issue by FDiskas** [brigand/babel-plugin-flow-react-proptypes#188]
"babel-plugin-flow-react-proptypes": "19.0.0"
babel: 7.0.0.0-beta.39

```
export type TProductFrontendCategoriesRaw = {
  [id: string]: string[],
};
```

**Comment by FDiskas** [comment]
but why it's a problem?
https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/5d4e193779d5dd5fef997d8d4ca1d4375d356f8b/src/__tests__/objectof-mixed-indexers-named-test.js#L5-L19

**Comment by FDiskas** [comment]
![error](https://i.imgur.com/cVIRjd1.png)

**Comment by FDiskas** [comment]
.babelrc
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-stage-2",
    "@babel/preset-flow",
    "@babel/preset-react"
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "polyfill": false,
        "regenerator": true,
        "moduleName": "@babel/runtime"
      }
    ]
  ],
  "env": {
    "production": {
      "plugins": ["transform-react-constant-elements", "transform-react-remove-prop-types"]
    },
    "development": {
      "plugins": ["flow-react-proptypes", "react-hot-loader/babel"]
    },
    "test": {
      "plugins": [
        "babel-plugin-react-docgen",
        {
          "DOC_GEN_COLLECTION_NAME": "MY_REACT_DOCS",
          "resolver": "findAllExportedComponentDefinitions",
          "includeMethods": true
        }
      ]
    }
  }
}
```

**Comment by brigand** [comment]
This change happened [here](https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/182).

There isn't a way to express this type with PropTypes, but we could create a custom prop type for it. 

For now, I'll relax the checks. Published as 19.1.0. I don't know when I'll have time to implement it properly, but PRs are very welcome.

**Comment by FDiskas** [comment]
maybe you can find something useful https://github.com/atlassian/babel-plugin-react-flow-props-to-prop-types :sound:

**Comment by brigand** [comment]
@FDiskas from their readme:

> ### Unsupported:
> `{ a: number, [b: string]: number }` Combining properties and indexers
> `{ [a: string]: number, [b: string]: number }` Multiple indexers
