### ISSUE TITLE
Cannot read property 'name' of null for anonymous Class components

### ISSUE THREAD

**Issue by emattias** [brigand/babel-plugin-flow-react-proptypes#192]
This code: 

```js
import * as React from 'react'

type Props = {
  children: React.Node
}

export const MyComponent = class extends React.Component<Props> {
  render() {
    return (
      <div>
        {this.props.children}
      </div>
    )
  }
}
```

results this error:

`Cannot read property 'name' of null`

If I give the class a name the error dissappears:

```js
import * as React from 'react'

type Props = {
  children: React.Node
}

export const MyComponent = class COMPONENTCLASSNAME extends React.Component<Props> {
  render() {
    return (
      <div>
        {this.props.children}
      </div>
    )
  }
}
```
To me it looks like this is the same problem as with anonymous function components that was discussed in issue https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/66 and fixed in PR https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/99

Here's a link to the the error triggering code in the babel repl (**You need to add the `babel-plugin-flow-react-proptypes` manually in the plugin section in the sidebar to get the error**): 

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA0wCeYWcACsWOgLxwDeNcOLgAWwADYATSgDsAXJiowAdADkIErDQC-dLAA9IsIRGmp4AWQYBhEpGlZp8HrjFp0-mA4npseZTfATBxgAHnYITgA-PgE4GQ0oAAoAShjBQUoYAFcoaThE2PS4EIlgADdIwqK-GFFUJTAOepFxKQcdauKAelKKquTYnS0gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

**Comment by brigand** [comment]
Thanks for the report. We couldn't support this in the past, but now we insert `static propTypes = {}` into the class, and babel can figure out the rest.

Fixed in 20.1.0.
