### ISSUE TITLE
Support sharing propTypes across files

### ISSUE THREAD

**Issue by brigand** [brigand/babel-plugin-flow-react-proptypes#2]
One limitation is that we can't look at other files from babel plugins. Because propTypes are only needed in development, and the plugin should be disabled in production, we'll always export any exported types as a special secret property, and when we import it we can access this property. Then any references to an imported type will be replaced with the raw propTypes object.

Albums.js

```js
export type Album = {
  id: string,
  title: string,
  coverImage: {
    id: string,
    src: string
  },
  description: string,
  userIsFollowing: boolean,
  stats: {
    likes: number,
  },
}
```

AlbumDetails.js

```js
import React from 'react';
import type {Album} from '../../models/Album';

type AlbumDetailsProps = {
  data: Album,
  otherStuff?: string
}

export default class AlbumDetails extends React.Component {
  props: AlbumDetailsProps;
  render() {...}
}
```

## Internals

It'll likely look something like this.

 - if no type alias: skip file
 - on first exported type alias for a file
  - append this to the end of Program

    ```js
    Object.defineProperty(module.exports, 'babel-plugin-flow-react-proptypes-exports', {
      value: {},
      configurable: true
    })
    ```
 - for each exported type alias
   - `let propTypeNodes = generatePropTypeAst(typeAliasAst)`
   - create and append to end of program:

        ```js
        module.exports
          ['babel-plugin-flow-react-proptypes-exports']
          .<<typeAliasName>> = <<propTypeNodes>>
        ```

**Comment by sckoh** [comment]
what's the progress of this feature? I try to import type but got the below warning

    warning.js?8a56:44Warning: Failed propType: AlbumDetails: prop type `data` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `Albums`.

**Comment by brigand** [comment]
@sckoh please share your code.

**Comment by brigand** [comment]
@sckoh I pushed a small fix for when there's no export from the other file, which may have been your issue. 0.7.1.

If that doesn't fix it for you, please include your code. Closing the issue for now because it seems to be working.
