### ISSUE TITLE
transforming recompose context props.

### ISSUE THREAD

**Issue by vaukalak** [brigand/babel-plugin-flow-react-proptypes#200]
I use recompose library, and using `getContext` enhancer:

```
/* @flow */
import { compose, getContext } from 'recompose';
import PropTypes from 'prop-types';

const enhancer = compose(
  getContext({
    someCallback: PropTypes.func,
  }),
);

export default enhancer;
```

I'd like to get this transformed via this plugin, something like that.

```
/* @flow */
import { compose, getContext } from 'recompose';

const enhancer = compose(
  getContext({
    someCallback: Function,
  }),
);

export default enhancer;
```

I understand that this is very low priority issue, and there's no straightforward way to implement this. But I just would like to create this issue as discussion point.

**Comment by brigand** [comment]
Hi there,

This only looks right by coincidence, e.g. here this parses as a reference to the variable `Function`, not a type annotation. We'd have to significantly alter runtime behavior for this code or concept to work, breaking assumptions people may have about the code. In the case of this plugin, all it does is potentially add more warnings to the console.

Going to close this as it's out of scope for this project.
