### ISSUE TITLE
Error when union types

### ISSUE THREAD

**Issue by snatvb** [brigand/babel-plugin-flow-react-proptypes#204]
Hello. When I try union types with three dots, then i get this error:
`Cannot read property 'forEach' of undefined
at convertToPropTypes node_modules/babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js:185:19`

Example:
```javascript
// file foo.js
export type WithId = {|
  fooId: string,
|}
```
```javascript
// file bar.js
import type { WithId } from './foo'

export type Bar = {|
  name: string,
  ...WithId,
|}
```
```javascript
import type { Bar } from './bar'

type Props = {
  bar: Bar,
}
```

Why?

**Comment by brigand** [comment]
Thanks for the report. Published as v21.1.1.
