### ISSUE TITLE
Required prop, but flow doesn't care

### ISSUE THREAD

**Issue by csterritt** [brigand/babel-plugin-flow-react-proptypes#21]
Hello -- sorry if I'm doing this wrong.

I've installed your plugin and it's great (don't have to declare things twice!), except for the following situation.

I have a class (important bits below):

```js
type CategoryProps = {
  article_count: number,
  id: number,
  is_selected: bool,
  name: string,
  visitCategory: (id: number) => void,
  deleteCategory: (id: number) => void,
  renameCategory: (id: number, name: string) => void
}


class Category extends Component {
  props: CategoryProps;

  constructor(props) {
    super(props);
    (this:any).onClick = this.onClick.bind(this);
    (this:any).onDelete = this.onDelete.bind(this);
    (this:any).onDeleteConfirmed = this.onDeleteConfirmed.bind(this);
    (this:any).onRename = this.onRename.bind(this);
    (this:any).onRenameConfirmed = this.onRenameConfirmed.bind(this);
    (this:any).onToggleEditDeleteMenu = this.onToggleEditDeleteMenu.bind(this);
  }

  //...
```

And a use thereof in another file:

```js
    const categories = this.props.categories.map(category => {
      return <Category article_count={category.article_count}
                       id={category.id}
                       is_selected={this.props.current_category.id === category.id}
                       key={category.id}
                       name={category.name}/>
    });
```

And everyone is happy.

However, if I change the last line of the invocation to `names={category.name}`, then flow is still perfectly happy, even though at runtime in the browser I get the right `Required prop 'name' was not specified in 'Category'.` error.

Am I misunderstanding something?  I believe that the type declaration makes `name` a required field, and the runtime error agrees, but flow doesn't care.

Thanks!

**Comment by brigand** [comment]
You can do `name?: string` to make it optional.

**Comment by csterritt** [comment]
Sorry, I guess I'm as confusing as ever :-) -- I *do* want name to be required.  My problem is that (I thought) flow would tell me if I skipped a required property.  Is this wrong?

**Comment by brigand** [comment]
Huh, I dunno. I haven't used flow on any serious projects yet, I just use the type annotations as docs/better proptypes syntax.

**Comment by csterritt** [comment]
Well, thanks again for the plugin -- I'll dig around and see if I can turn something up.

**Comment by sckoh** [comment]
Is it because of flow is a static type checker, category.name is not known until runtime (acquired from api?) so flow do not complain.

**Comment by csterritt** [comment]
@sckoh No, both the call (the second code block) and the code being called (the first code block) are there, and static (in effect).  So I'd think it should catch the error.

**Comment by brigand** [comment]
This seems like a problem with flow, not this plugin, so I'm closing the issue. You could report/ask about it in flow's issue tracker.
