### ISSUE TITLE
aria-{name} and data-{name} props do not work

### ISSUE THREAD

**Issue by andreawyss** [brigand/babel-plugin-flow-react-proptypes#219]
props that contain a dash "-" do not work.
These where working with Babel 6 and previous version of the plugin.

To reproduce add these props to the basic-test.js example: 

type FooProps = {
  'aria-label': string, // a required aria prop
  'data-e2e': string, // a required data prop
}

Proptype validation fail even when the given prop is present.

Warning: Failed prop type: The prop `"data-e2e"` is marked as required in `ButtonComponent`, but its value is `undefined`.

**Comment by brigand** [comment]
Hi. This is what I see generated for that in babel 7.

```js
{
  "aria-label": _propTypes.default.string.isRequired,
  "data-e2e": _propTypes.default.string.isRequired
}
```

If React doesn't handle hyphens in the prop names correctly here (I haven't checked), then is there some output that would be more compatible?

The warning is coming from React applying the prop-type check on the property, with the expected name in the message, so this looks unlikely to be a bug in this plugin. Closing for now, but happy to reopen if there's something actionable.
