### ISSUE TITLE
Does not work with contextTypes

### ISSUE THREAD

**Issue by yuri-karadzhov** [brigand/babel-plugin-flow-react-proptypes#22]
Unfortunately it does not work with contextTypes, that should be pretty much the same.

**Comment by brigand** [comment]
I don't think I'm going to support contextTypes with this plugin, as it's intended for use only in development, and contextTypes affects the behavior of your application. This means if you only used it in development, it'd break production builds of your app.

**Comment by rosskevin** [comment]
I think this plugin is/will be used in production, especially for libraries that are complex and are used as either commonjs or umd modules.  While some may not want to use it in production and you are right that it wouldn't work both ways, it would be nice to have this option.

**Comment by MrCheater** [comment]
+1
