### ISSUE TITLE
Issue when using with rollup imports

### ISSUE THREAD

**Issue by romeovs** [brigand/babel-plugin-flow-react-proptypes#223]
The import renaming breaks with rollup. For example:

```
// foo.js
import { type Bar } from "bar"

type Props = {
  bar : Bar,
}
function Foo(props : Props) {/* ... */}
```

When building `foo.js` with rollup, I get this error:
```
'bpfrpt_proptype_Bar' is not exported by bar
```

This presumably happens because the import gets transformed from:
```
import { type Bar } from "bar"
```
to
```
import { type bpfrpt_proptype_Bar } from "bar"
```
which a) is no longer a type import so does not get stripped and b) `bpfrpt_proptype_Bar` indeed does not exist in `bar`.

This only happens when bar is a non-local import.

Has anyone run into this issue?

**Comment by brigand** [comment]
Hi. So we have a test for this [here](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/__tests__/import-non-relative.js) with [this snapshot](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/__tests__/__snapshots__/import-non-relative.js.snap). I also tried with exactly `import { type Bar } from "bar"` and using `Bar` in the type for the component props, where the import seems to get completely stripped.

Could you share your babel config and the exact code that give the error (if you weren't literally using 'bar' when trying this)?

**Comment by romeovs** [comment]
I can't reproduce this. Closing.
