### ISSUE TITLE
Error on import type

### ISSUE THREAD

**Issue by Kerumen** [brigand/babel-plugin-flow-react-proptypes#23]
I get this error on a React Native file: `Cannot read property 'name' of undefined` ([here](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/5b17cab2e7a72a632b5e70fd3a809c82952ddb09/src/index.js#L112)).

The problematic line is [here](https://github.com/facebook/react-native/blob/v0.26.3/Libraries/CustomComponents/Navigator/Navigation/NavigationContext.js#L39).

EDIT: The file has a `@noflow` comment. Maybe it's worth checking this before trying to transform it?

**Comment by brigand** [comment]
@Kerumen thanks for the report.

This happens because I assumed only `import {Type} from './x'` was valid (note the `{}`s), but I can add support for what looks like a default type import.

If you're exporting a type, it should probably work despite the noflow flag.

**Comment by brigand** [comment]
This is fixed in 0.7.2. Let me know if it works for you.

**Comment by Kerumen** [comment]
Yes it works!
