### ISSUE TITLE
Does not apply propTypes using `$Exact<>`

### ISSUE THREAD

**Issue by justinanastos** [brigand/babel-plugin-flow-react-proptypes#47]
I am using `$Exact<>` to ensure that *only* certain props are passed to a component (flow will fail if any others are passed). I understand that checking for extraneous props is not easily handled with `propTypes`, but *all* type definitions wrapped in `$Exact<>` are ignored.

This works:

```javascript

type ComponentProps = {
    someProp: string,
};
```

This does write any `propType` checks:

```javascript
type ComponentProps = $Exact<{
    someProp: string,
}>;
```

**Comment by brigand** [comment]
@justinanastos do you have docs on this? I can't find them.

**Comment by justinanastos** [comment]
It's still undocumented :( My understanding is it's the same as the `{| |}` operator described in the [v0.32.0 changelog](https://github.com/facebook/flow/blob/master/Changelog.md#v0320). The missing documentation is listed as an issue in facebook/flow#2462 in [this comment](https://github.com/facebook/flow/issues/2464#issuecomment-247606625). I think the *correct* way to use it is with `{| |}` but I am not using it because eslint (and babel-eslint) does not yet allow it.

**Comment by brigand** [comment]
Cool, looks like babel already supports it too, at least the latest version.

I need to think about what the resulting code should look like. Feel free to share any ideas you have.

**Comment by justinanastos** [comment]
Looks like you're right! With an update to babel and eslint this eslint checks no problem.

**Comment by gabro** [comment]
See also https://github.com/facebook/flow/pull/2525 for the WIP documentation ;-)

**Comment by gcanti** [comment]
https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/51
