### ISSUE TITLE
children: PropTypes.node

### ISSUE THREAD

**Issue by brettstack** [brigand/babel-plugin-flow-react-proptypes#48]
I'm unable to find an example for `PropTypes.node` - could you add one to the README?

**Comment by brigand** [comment]
What would that look like as a flow annotation?

**Comment by brettstack** [comment]
That's what I'm asking. I'd love to be able to define my propTypes in Flow,
but this would be a huge limitation if you can't do it.

**Comment by brigand** [comment]
From the react docs

```js
    // Anything that can be rendered: numbers, strings, elements or an array
    // (or fragment) containing these types.
    optionalNode: React.PropTypes.node,
```

So the prop would be a pretty complicated union type annotation. If there's an easier way to write this that's valid in flow we can add special support.

The best thing for now is probably to mark it as `any`, which means anything except undefined (or null, I think).

**Comment by brettstack** [comment]
any will do for now. Can you add that to the README and maybe someone will
come up with a better solution.

**Comment by brigand** [comment]
I'm not going to put it in the readme, but hopefully someone else asks about it in an issue, and comes with solutions 😄

**Comment by MoOx** [comment]
The simplest way is to use

children: any

or maybe

- children: React$Element<any>

**Comment by brettstack** [comment]
Thanks, @MoOx. Where does `React$Element` come from? I see in #14 you use `ReactElement`. I stole your code and dropped it into a common `_types.js` file:

```
export type ReactComponentState = {
  [key: string]: any
}

export type ReactElement = any

export type ReactNode = (
  state: ReactComponentState,
  setState: (state: ReactComponentState) => void
) => ReactElement
```

It might be worth it for this lib to export these. Even if it's just `export type ReactNode = any`, at least we would have a placeholder we could use for now.

**Comment by MoOx** [comment]
It should more be React$Element<any>.
This comes from React core (not sure from where, but it's used here https://github.com/facebook/react/blob/16ac141f44583bd59f95f5b420a66bfcef01865e/flow/environment.js#L20)

**Comment by brigand** [comment]
Isn't that just for elements, being objects with properties `{type, props, key, ref}`?

**Comment by MoOx** [comment]
Yeah so maybe...

children: number | string | React$Element<any> | Array<number | string | React$Element<any>>

But it will become complicated to handle...

**Comment by brigand** [comment]
The thing is... you can already kinda do that. The only thing special you need to do is make a file types.js:

```js
export type ReactNode = 
  number
  | string
  | {type: string | function, props: object, key?: any, ref?: string | function}
  | Array
```

And then import that in your component

```js
import type {ReactNode} from './types';
type FooProps = {
  x: ReactNode
}
```

So us adding extra support for it doesn't really change anything. Unless we want to do a string match on GenericTypeAnnotation for 'ReactNode' or similar... which is gross and won't work well if you're actually using flow as a type checker.

**Comment by brigand** [comment]
Actually that doesn't work currently, it seems to ignore the type annotation, likely because it's not an object.

**Comment by brettstack** [comment]
I don't have experience with flow or Babel internals, but that's what I was
thinking. You export ReactNode and transform to PrppTypes.Node.

**Comment by brigand** [comment]
Cool. I don't know when I'll have time to work on this. Feel free to send a PR if you have the time.

**Comment by wesm87** [comment]
This seems to work for me:

```
import type { Children } from 'react';

type Props = {
  children: Children,
};
```

**Comment by limscoder** [comment]
I've been using this for `node` in my flow `children?: React.Element<*>`

**Comment by mhaas** [comment]
I think this should be working these days - if you use a shared exported type, you will get what you need.

**Comment by brigand** [comment]
@mhaas fixed this, so try the latest version and let us know if you have any issues.
