### ISSUE TITLE
eslint react/prop-types: 'property' "is missing in props validation"

### ISSUE THREAD

**Issue by brettstack** [brigand/babel-plugin-flow-react-proptypes#49]
Any solution for getting this plugin to play nicely with the `react/prop-types` eslint rule? This rule warns you when you use a prop that you have not defined in your `propTypes`. For now I'm just going to silence it, but it would be awesome if we could get a companion eslint rule  that works with this plugin.

**Comment by brigand** [comment]
That'd be a whole other project, but convertPropTypes.js might be useful to it. If you decide to take it on, I'll link to it in the readme.

**Comment by JelteF** [comment]
For me that's working fine, even without this library. Maybe you should update eslint or the react plugin.

**Comment by brettstack** [comment]
@JelteF it's that it's not working with this library. That is, it was working when I was defining my props using PropTypes directly. If you have a solution, please share. :)

**Comment by ctrlplusb** [comment]
@brettstack Have you tried https://github.com/gajus/eslint-plugin-flowtype

**Comment by dozoisch** [comment]
For me updating to latest eslint-plugin-react fixed it @brettstack

**Comment by brigand** [comment]
Cool, looks like this is resolved 😄
