### ISSUE TITLE
Not working with react native

### ISSUE THREAD

**Issue by StevePotter** [brigand/babel-plugin-flow-react-proptypes#53]
1) Install React Native 0.35+ (I didn't test on another platform)

In console
```
react-native init myapp
cd myapp
```
Install via readme instructions.  Add foo.js by copy/pasting from readme.  In index.io.js, do
```
require('./foo')
```
Then run
```
react-native run-ios
```
To see the generated output, go to http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false

You'll see Foo there, but no proptypes.   I tested on multiple React Native  projects and the plugin simply doesn't work.  Can I get some help?  Would you like me to post the project for you?

**Comment by brigand** [comment]
I'll try to reproduce. Share your .babelrc

**Comment by brigand** [comment]
I think I was able to reproduce it at first, but I may have just missed it in the output. 

Here's the files I changed: https://gist.github.com/6f647717428dc8effba671bf3f9c81a8

**Comment by brigand** [comment]
Closing the issue for now.

**Comment by StevePotter** [comment]
Hey @brigand thanks for your efforts with this.  Turns out it was just the plugin name.  The docs say "flow-react-proptypes" but your example uses "babel-plugin-flow-react-proptypes".  Do the docs need updated, or in this case the name is supposed to be different?

**Comment by brigand** [comment]
Either should work. Babel automatically prefixes it with 'babel-plugin-'.

**Comment by StevePotter** [comment]
Thanks, nice to know
