### ISSUE TITLE
Functional components often not detected

### ISSUE THREAD

**Issue by Rovack** [brigand/babel-plugin-flow-react-proptypes#54]
While this plugin does have some support for detecting stateless functional components, and consequently generating propTypes for them, there are several scenarios where it fails to do so.

Specifically, if such a component's function doesn't return JSX directly, but rather returns a variable to which JSX was previously assigned, it will not be detected.

For example, with the following code, not passing `mandatoryString` will successfully trigger an error:
```
// @flow

import React from 'react';
import { Text } from 'react-native';

type Props = {
  mandatoryString : string,
};

const MyComponent = (props : Props) => {
  return <Text>{props.mandatoryString}</Text>;
};

export default MyComponent;
```

However, if we change `MyComponent` to the following, the error will no longer be triggered:
```
const MyComponent = (props : Props) => {
  const component = <Text>{props.mandatoryString}</Text>;
  return component;
};
```
*(I happen to be using React Native in these examples, although I'm pretty sure the exact same problem would happen with regular React.)*

It seems to me this might be caused by `isFunctionalReactComponent`'s naive implementation, checking `t.isReturnStatement(b) && t.isJSXElement(b.argument)`, but not taking into account the case where the argument to `return` is not a JSX statement itself, but a variable containing JSX.

Now, this issue in itself is quite confusing, but it's at least possible to work around it by just always returning JSX directly.

What's really problematic is that if the code is wrapped in any way, the check for functional React components will also fail.
One example of when that might happen is when jest monitors code coverage. As it turns out, if jest tests are run with code coverage enabled, this plugin will not create propTypes for any functional components whatsoever.

This means there's actually no way to write tests for prop validation, when using this plugin with functional React components.

**Comment by Rovack** [comment]
Thanks for the (incredibly) quick response!

I think if the first part were fixed, that'd already be a great improvement.

As for code coverage, I haven't looked deeply enough into the internals of jest (or rather istanbul) to be sure, but I suspect it might be related to the first issue.
If we find that this still happens after the first part is fixed, I'll investigate it further.

**Comment by brigand** [comment]
I think I got it working. Try 0.16.0.

**Comment by Rovack** [comment]
Verified that this solves the first problem described in the issue.

Of course, this approach stops working once a separate function is involved (based on a real-world scenario that we encountered):
```
const createComponent = (props : Props) => (
  <Text>{props.mandatoryString}</Text>
);

const MyComponent = (props : Props) => {
  const component = createComponent(props);
  return component;
};
```

Looks like the coverage issue is also not quite resolved yet.

Should I open a separate issue(s) for those?

**Comment by brigand** [comment]
The separate function requires type analysis which is out of scope for this project.

Yeah, create a separate issue for functions in expressions. Are you going to try to tackle it?

**Comment by brigand** [comment]
Actually, maybe we could handle something like:

```js
const MyComponent = (props: Props) : JSXElement => {
  return foo();
}
```

You can create another issue for that.

**Comment by Rovack** [comment]
Actually, that would be perfect!
I was already looking into a way to annotate React functional components to make this problem easier, but somehow it never occurred to me that just annotating the return type as JSX with Flow might be all we need here. :P

I'll open an issue for that right now.

**Comment by Rovack** [comment]
Opened https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/55.
(I use React's `ReactElement` and not Babel's `JSXElement` in the example there just because it seems a bit more explicit to me, but really I suppose any kind of annotation will work.)
