### ISSUE TITLE
Redux connected components

### ISSUE THREAD

**Issue by ismay** [brigand/babel-plugin-flow-react-proptypes#56]
I've not been able to get this plugin to work with react es6 class containers / components that are using the redux `connect` decorator. Should it work, or is this not possible?

Because none of the examples as outlined in the readme work for me (although the plugin does work perfectly for me with pure components).

**Comment by brigand** [comment]
You have to write it like this:

```js
class MyComponent {
  props: Props;
}
export default connect()(MyComponent);
```

I'd accept a PR adding decorator support. I might implement it eventually but it's not a priority, especially considering it's disabled in babel pending spec changes.

**Comment by ismay** [comment]
I did try it without the decorator support, but I'll double check and see if I can get it to work in the way that you describe. Will let you know if I encounter anything.

**Comment by ismay** [comment]
Ok, I tried it again for a container component and for a regular es6 class component. In both cases `babel-plugin-flow-react-proptypes` does not set the proptypes for me. In my other use cases it does work correctly:

```
/* @flow */

import { connect } from 'react-redux';
import React, { Component } from 'react';
import GapAnalysis from '../pages/GapAnalysis';
import { requestFacts, requestIndicators, requestVersions } from '../actions';

type Props = {
  facts: Object[],
  indicators: Object[],
  versions: Object[],
  requestFacts: Function,
  requestIndicators: Function,
  requestVersions: Function,
};

export class Unconnected extends Component {
  componentWillMount() {
    this.props.requestIndicators();
    this.props.requestVersions();
  }

  props: Props;

  render() {
    return <GapAnalysis {...this.props} />;
  }
}

const mapStateToProps = (state) => ({
  facts: state.facts.items,
  indicators: state.indicators.items,
  versions: state.versions.items,
});

const actions = { requestFacts, requestIndicators, requestVersions };

export default connect(mapStateToProps, actions)(Unconnected);
```

**Comment by brigand** [comment]
That exact code works for me.

```
$ babel --presets es2015,react --plugins flow-react-proptypes a.js
// ...
Unconnected.propTypes = {
  facts: require('react').PropTypes.arrayOf(require('react').PropTypes.object).isRequired,
  indicators: require('react').PropTypes.arrayOf(require('react').PropTypes.object).isRequired,
  versions: require('react').PropTypes.arrayOf(require('react').PropTypes.object).isRequired,
  requestFacts: require('react').PropTypes.func.isRequired,
  requestIndicators: require('react').PropTypes.func.isRequired,
  requestVersions: require('react').PropTypes.func.isRequired
};
// ...
```

**Comment by ismay** [comment]
Hmm strange, I must be doing something wrong then. I think this issue can be closed then, and should I find anything I'll let you know. Thanks for the feedback!
