### ISSUE TITLE
Never generate isRequired for boolean properties?

### ISSUE THREAD

**Issue by DJCordhose** [brigand/babel-plugin-flow-react-proptypes#64]
Having these Props

```
type Props = {
  open: boolean;
}
```

you will get propTypes so like there, ie.e open will be required:

```
class MyComponent extends Component<void, Props, void> {
  static propTypes = {
    open: PropTypes.bool.isRequired
  };
}
```
However, if you leave open as undefined when calling the component, this is totally fine, with Flow and also with JavaScript. But React now produces an error when no property is passed. 

Doing it the other way round, like

```
type Props = {
  open?: boolean;
}
```

now produces a good definition of propTypes

```
class MyComponent extends Component<void, Props, void> {
  static propTypes = {
    open: PropTypes.bool
  };
}
```

but now Flow is no longer happy if I try and access `this.props.open` without additional check.

**Here comes my questions:**

Would it be a good idea to never generate `isRequired` for **boolean** properties?

**Comment by brigand** [comment]
If it's optional, you should guard against it. This is flow doing what it's supposed to do :-)

**Comment by DJCordhose** [comment]
Can you think of a situation where implicitly converting from undefined/null to boolean would be dangerous?

I have never seen any JavaScript code that would check for null/undefined before using it as a boolean. But of course I might be missing something here.

**Comment by brigand** [comment]
That sounds like an issue with flow's handling of nullable types.

**Comment by DJCordhose** [comment]
Possible, but more likely that I am wrong/confused or React handles those booleans strangely. Will think about it...
