### ISSUE TITLE
React.createClass correct usage

### ISSUE THREAD

**Issue by charlesoconor** [brigand/babel-plugin-flow-react-proptypes#69]
Its says the the readme that this plugin will work with `React.createClass`. Is there an example of how to annotate the object correctly. I've tried
```javascript
const defaultProps: any = null; 
type PropTypes = {
  name: string
}
const Comp: _ReactClass<*, PropTypes, *, *> = React.createClass({
  props:(defaultProps: PropTypes),
  ...
})
```

In the output has the proptypes but isn't connecting them. Any help would be greatly appreciated

**Comment by brigand** [comment]
I think createClass worked at some point in the past, but we don't have any tests for it, and when I try it I'm not seeing any propTypes generated.

I'm pretty busy currently, but I'd definitely accept a PR adding support for this. For now I'm going to remove it from the readme.

**Comment by harsimranb** [comment]
`React.createClass` has been deprecared in React 15.5.  https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html.

**Comment by brigand** [comment]
Yeah, I think we can let createClass die now.
