### ISSUE TITLE
aren't propTypes removed in production anyway?

### ISSUE THREAD

**Issue by faceyspacey** [brigand/babel-plugin-flow-react-proptypes#70]
I'm wondering because I'm trying to determine the correct usage for an open source package. I'm thinking it shouldn't be set only in development so that users can decide.

**Comment by brigand** [comment]
Hmm... we might want to add an option for adding a NODE_ENV check so minifiers can strip it for production.

**Comment by faceyspacey** [comment]
yea, but aren't the propTypes removed in production automatically??

**Comment by brigand** [comment]
Nope. React doesn't check them in production, but they're still in the code.

**Comment by sohkai** [comment]
> Hmm... we might want to add an option for adding a NODE_ENV check so minifiers can strip it for production.

@brigand Was this ever implemented? AFAIK consumers of a library won't be able to run babel plugins like [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) on their imports unless they get messy with their `node_modules` so the only chance they have of stripping out prop types would be if the library had their prop types under `NODE_ENV` flags.

**Comment by brigand** [comment]
Yeah, we could add this, and since `require('prop-types')` is inline, it'll get hit by dead code elimination. I'll be pretty busy the next few days, but I'll add a reminder to do this if no one gets to it first.

**Comment by sohkai** [comment]
Cool! I don't mind helping out if you need some :).

**Comment by brigand** [comment]
@sohkai I'd love some help!
