### ISSUE TITLE
propTypes are not created if you assign props from a pre-defined type or if you import types from another file

### ISSUE THREAD

**Issue by faceyspacey** [brigand/babel-plugin-flow-react-proptypes#71]
For example the following won't work:

```
const Link = ({ href, children }: Props) =>
   <a href={href}>children</a>

type Props = {
   href: string,
   children: any,
}
```

whereas this will:

```
const Link = ({ href, children }: {
   href: string,
   children: any,
}) =>
   <a href={href}>children</a>
```

In addition, if you import types, from other files, the type won't in fact be created in the other file. There will be nothing there. That problem becomes even worse if you're using types imported from packages, e.g. the `react-redux` flowtypes, eg if you're doing something like the following you're screwed:

```
import React from 'react'
import { connect } from 'react-redux'
import type { Store } from 'redux'
import type { Connector } from 'react-redux'

import type { Href } from './hrefToUrl' // no flow type will be converted to a propType in the other file

type OwnProps = {
  href: Href, 
  children: any, 
}

type Props = {
  dispatch: Function,
} & OwnProps // doubt an intersection will work

type Context = {
  store: Store,
}

const Link = ({ href, children }: Props) => // Props wont work cuz its not defined here
   <a href={href} onPress={(e) => e.preventDefault() || dispatch({ type: 'FOO' })}>{children}</a>

const connector: Connector<OwnProps, Props> = connect() // yea right, not happening

export default connector(Link)
```

So in short, any serious code using redux (or any 3rd party types, *or any of your own imported files*) unfortunately won't work with this otherwise great package.

**Comment by faceyspacey** [comment]
my hunch is the 3rd party packages may be challenging to transpile, but you should at least be able to import types in your own code, and at the very least you should be able to assign a `Props` variable/type, rather than define it in place. That last one really will reduce redundancy. Redundancy in the same file is just depressing.

**Comment by brigand** [comment]
Thanks for the report!

Importing types from other files that are processed by this plugin, and explicitly export a type is a feature of this plugin. 

I'll look into these issues when I find time. If you want to take a stab at some of the issues that'd be great!

**Comment by max-mykhailenko** [comment]
My almost all types based on global `flow-typed`. Because I don't want to duplicate type definition in reducer and for components. And plugin replace all of them by `any` in component `propTypes`. When you plan to improve that? How I can help with it?

**Comment by brigand** [comment]
@max-mykhailenko supporting flow-typed would be a ton of extra code and require filesystem access, which isn't good in a babel plugin.

If you implement it in a fork, I'll put a link in the readme, but I don't want to maintain that feature.

**Comment by max-mykhailenko** [comment]
@brigand maybe you know another way to define types across the files, maybe `import` all definitions?

**Comment by brigand** [comment]
@max-mykhailenko you can import types in flow (`import type {Foo} from '...'`), and in some specific cases that works with this plugin, but only when both files are processed by this plugin and the type is an object.

**Comment by nezed** [comment]
I think this issue about [**Types intersection**](https://flow.org/en/docs/types/intersections/) with `&`, not only about importing types.

Here some demo:

```js
//@flow
import React from 'react'

type partialProps = {
  prop: string
}

// Imported type also produces incorrect `require('react').PropTypes.any` in transpiled code
// import type {partialProps} from '../external-file'

type Props = partialProps & {
  theme: ?Object
}

class PropTyped extends React.Component {
  props: Props

  render() {
    return <div />
  }
}
```

**Comment by max-mykhailenko** [comment]
After a little bit thinking about problem I decide that propTypes not necessary when I'm using flow. Flow shows all required props and help me call component with right arguments. API errors should be tested by API unit tests and propTypes created not for this.

**Comment by faceyspacey** [comment]
By the way, this issue still occurs if you don't put the flow types before they are used.  Typically with Flow it doesn't matter what order the types come in (they are hoisted), but with the babel plugin, they have to be defined before used.

Not the biggest issue, but worth mentioning. The previous fix for intersections seemed to fix the main problem.
