### ISSUE TITLE
React 15.5 moved PropTypes to separate package

### ISSUE THREAD

**Issue by simonsmith** [brigand/babel-plugin-flow-react-proptypes#72]
Detail: https://facebook.github.io/react/blog/#migrating-from-react.proptypes
Package: https://www.npmjs.com/package/prop-types

It currently still works under the `React` object but throws a warning in the console. I suppose a change could be made now and a major version released and nothing would need to change for `16.x`

**Comment by brigand** [comment]
Thanks! Published as 1.0.0.
