### ISSUE TITLE
hasReactElementTypeAnnotationReturn() false positivies

### ISSUE THREAD

**Issue by eugene1g** [brigand/babel-plugin-flow-react-proptypes#97]
Hi,

[hasReactElementTypeAnnotationReturn](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/util.js#L59) is currently too eager - it returns `true` by default. This means that anything that is an `ArrowFunctionExpression` + `has a returnType` will be treated as a React component. For example ` const addOne = (num: number) : number => (num+1)` meets that criteria but it's not a react component.

I understand the plugin focuses on React components, but projects can have many such little helper functions spread across the codebase and currently they break the build process. I think `hasReactElementTypeAnnotationReturn` should probably default to `false` until proven - with some certainty - that a random function is in fact subject to React prop-types and not just regular Flow rules.

**Comment by eugene1g** [comment]
I think the situation is more nuanced than I first thought because the plugin works very well in many other cases. At any rate, I can use the useful directive of "'no babel-plugin-flow-react-proptypes'" to ignore messy files for now.

**Comment by brigand** [comment]
@eugene1g thanks for the report. Fixed the bug and published as 3.1.2. Now it requires the function return value annotation to be ReactElement. Is this the right behavior?

**Comment by eugene1g** [comment]
Awesome! Fixes my use-case right away. Thanks!
